apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend-service
    app: assignment-app
spec:
  type: LoadBalancer
  selector:
    name: frontend
    app: assignment-app
  ports:
    - port: 80
      targetPort: 80
