apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: assignment-app
spec:
  selector:
    name: redis
    app: assignment-app
  ports:
    - port: 6379
      targetPort: 6379
